[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.2",
    "diskcache>=5.6.3",
    "eth-account>=0.13.7",
    "fastapi>=0.116.1",
    "stellar-sdk>=12.3.0",
    "web3>=7.12.1",
    "x402>=0.1.5",
]
