# dev.stellar.toml
ACCOUNTS = ["GDHH5ISNXNLNMVW62GO45JAFRB2TATB5GINMVZ43TAAVC3BV3GYOTCJ6"]
SIGNING_KEY = "GDHH5ISNXNLNMVW62GO45JAFRB2TATB5GINMVZ43TAAVC3BV3GYOTCJ6"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

TRANSFER_SERVER_SEP0024 = "http://localhost:8080/sep24"
WEB_AUTH_ENDPOINT = "http://localhost:8080/auth"
KYC_SERVER = "http://localhost:8080/sep12"
ANCHOR_QUOTE_SERVER = "http://localhost:8080/sep38"
TRANSFER_SERVER = "http://localhost:8080/sep6"

[[CURRENCIES]]
code = "USDC"
issuer = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
status = "test"
is_asset_anchored = false
desc = "USD Coin issued by Circle"

[DOCUMENTATION]
ORG_NAME = "x402-Ramp Test Anchor"
ORG_URL = "https://x402-ramp.com"
ORG_DESCRIPTION = "Programmable payment rail anchor running on Stellar testnet"